# Generated by Selenium IDE
import pytest
import time
import json
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

PATH = "C:\\Program Files (x86)\\chromedriver.exe"
#PATH = "C:\Users\gold.aptaworks\AppData\Local\Google\Chrome\User Data\Default"
#driver = webdriver.Chrome(PATH)
vars = {}

options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--ignore-ssl-errors')
driver = webdriver.Chrome(PATH)

  #def teardown_method(self, method):
#driver.quit()
  
#  def test_test1(self):
#driver.set_page_load_timeout(10)
driver.get("https://www.gsmarena.com/")
driver.set_window_size(784, 816)
time.sleep(5)
driver.find_element(By.ID, "topsearch-text").click()
driver.find_element(By.ID, "topsearch-text").send_keys("iphone 13")
driver.find_element(By.ID, "topsearch-text").send_keys(Keys.ENTER)
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) img").click()
element = driver.find_element(By.LINK_TEXT, "Announced")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
driver.find_element(By.CSS_SELECTOR, ".article-info .article-info-meta-link:nth-child(4) > a").click()
driver.find_element(By.ID, "sSearch2").click()
driver.find_element(By.ID, "sSearch2").send_keys("asus rog phone 8")
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) span").click()
driver.close()