# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    # Test name: test1
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://www.gsmarena.com/")
    # 2 | setWindowSize | 784x816 |  | 
    self.driver.set_window_size(784, 816)
    # 3 | click | id=topsearch-text |  | 
    self.driver.find_element(By.ID, "topsearch-text").click()
    # 4 | type | id=topsearch-text | iphone 13 | 
    self.driver.find_element(By.ID, "topsearch-text").send_keys("iphone 13")
    # 5 | sendKeys | id=topsearch-text | ${KEY_ENTER} | 
    self.driver.find_element(By.ID, "topsearch-text").send_keys(Keys.ENTER)
    # 6 | click | css=li:nth-child(1) img |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) img").click()
    # 7 | mouseOver | linkText=Announced |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Announced")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | click | css=.article-info .article-info-meta-link:nth-child(4) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".article-info .article-info-meta-link:nth-child(4) > a").click()
    # 9 | click | id=sSearch2 |  | 
    self.driver.find_element(By.ID, "sSearch2").click()
    # 10 | type | id=sSearch2 | asus rog phone 8 | 
    self.driver.find_element(By.ID, "sSearch2").send_keys("asus rog phone 8")
    # 11 | click | css=li:nth-child(1) span |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) span").click()
    # 12 | close |  |  | 
    self.driver.close()
  
